"""create suppliers tables

Revision ID: 721c75b75ec6
Revises: 660b7c21a136
Create Date: 2026-01-07 10:36:31.932732

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import mysql
if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = '721c75b75ec6'
down_revision = '660b7c21a136'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_invoices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('supplier_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purchase_order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('invoice_date', mysql.DATETIME(timezone=True), nullable=False),
    sa.Column('due_date', mysql.DATETIME(timezone=True), nullable=True),
    sa.Column('status', mysql.ENUM('DRAFT', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', 'VOID'), nullable=False),
    sa.Column('payment_status', mysql.ENUM('PENDING', 'PARTIAL', 'COMPLETED', 'FAILED'), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('other_charges', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('amount_paid', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('balance_due', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_invoices_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoices')),
    sa.UniqueConstraint('supplier_id', 'invoice_number', name='uq_supplier_invoice')
    )
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoices_invoice_number'), ['invoice_number'], unique=False)

    op.create_table('supplier_invoice_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('purchase_order_item_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', mysql.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('received_quantity', mysql.INTEGER(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], name=op.f('fk_supplier_invoice_items_invoice_id_supplier_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_supplier_invoice_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], name=op.f('fk_supplier_invoice_items_purchase_order_item_id_purchase_order_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_invoice_items'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_invoice_items')
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoices_invoice_number'))

    op.drop_table('supplier_invoices')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
