"""edit fields on models

Revision ID: c0d8ca904752
Revises: 4f648b4ad6a4
Create Date: 2026-01-19 12:08:38.180865

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash, FernetBackend
from advanced_alchemy.types.encrypted_string import PGCryptoBackend
from advanced_alchemy.types.password_hash.argon2 import Argon2Hasher
from advanced_alchemy.types.password_hash.passlib import PasslibHasher
from advanced_alchemy.types.password_hash.pwdlib import PwdlibHasher
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject
sa.PasswordHash = PasswordHash
sa.Argon2Hasher = Argon2Hasher
sa.PasslibHasher = PasslibHasher
sa.PwdlibHasher = PwdlibHasher
sa.FernetBackend = FernetBackend
sa.PGCryptoBackend = PGCryptoBackend

# revision identifiers, used by Alembic.
revision = 'c0d8ca904752'
down_revision = '4f648b4ad6a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_order_items_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchase_order_items_product_id_products'), 'products', ['product_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_supplier_id_suppliers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supplier_invoices_supplier_id_suppliers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_supplier_invoices_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_supplier_invoices_supplier_id_suppliers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_supplier_invoices_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_supplier_invoices_purchase_order_id_purchase_orders'), 'purchase_orders', ['purchase_order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_orders_supplier_id_suppliers'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchase_orders_supplier_id_suppliers'), 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_purchase_order_items_product_id_products'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_purchase_order_items_product_id_products'), 'products', ['product_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
